### ISSUE TITLE
Pestle 1.5.1 and 1.5.2 Release

### ISSUE THREAD

**Issue by astorm** [fballiano/homebrew-mageutils#3]
👋 Hey there -- we just released pestle 1.5.1 and a quick 1.5.2 right after that.  

    $ openssl sha256 pestle-1-5-1.phar 
    SHA256(pestle-1-5-1.phar)= 438cfe74bfd860d52570e0dd1a1a2b09d57ced19bd2ea63020a1db132361e553

    $ openssl sha256 pestle-1-5-2.phar 
    SHA256(pestle-1-5-2.phar)= 4796f9def1f0c08c646f6b9625f417134dcdc2a2ec34514bdc718d71b35c475b

and we're also going to try publishing them with versioned numbers

    curl -LO http://pestle.pulsestorm.net/pestle.phar
    curl -LO http://pestle.pulsestorm.net/pestle-1-5-2.phar
    curl -LO http://pestle.pulsestorm.net/pestle-1-5-1.phar

Not sure how any of the above will impact you, but did want to let you know.

**Comment by fballiano** [comment]
Hi @astorm, thank you very much for letting me know! I've updated the formula with the newest version, it now downloads directly from your server instead of mine (which for me is much better).

Thanks a lot!
